language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

notifications:
  email: false

before_install:
  - yarn global add codecov

script:
  - yarn run lint
  - yarn run build
  - yarn run build:dev
  - yarn run build:prod
  - yarn test

after_success:
  - codecov
