language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

notifications:
  email: false
  slack:
    rooms:
      - secure: "aV6tRmLPUAqGP3cnjTGOFVLS4kAB+DGyXqDU4WC6EGcGlojUPBwP6C/bzU5YCuMz6qE547LbN/1BYNFatJRqsg40fleN7ZYPwnArPiWRRg2rulIe5Fr0y04rzNcUiaYvNL6JoBjG/sGFLrBXPImC7Ovqg4eUHVtdGXP6jQD2fo/D2pDFijJEJDvHZldtywzguJT9qnX7pLjU521z63ka+v0mB4zYWpDeUkJNsBDUM5T+WK4gWwIkaCXdsBymKo+jFSmhynYhzm4C+Piq/fTd+/HGy5hWwCMhgsalwxZIDgde/BxYf+Z2HiubiDgyWNs9D4z8QaJAtTPtI+5ND7YzsmyRforjtTfYYnN/zzutUFYtsaafEJ9w/O8Gr3pKleW6Rrv3kwJGQ6aH0VkASDuRhqubRZU0ZEic3lJ69N8/LSyyTzNwkheYzVAsSMl9DRAigg6Be+sEbb7x4PZ6t6mxLutODA9DsNgpCf4CwVgGK877NstHBqS7u9rYmImN2i6LArSRnUlklRRNMCa8+6CnUWPHzCDnWv2hzhYTZxXVGcbW57ohktOJkPzmLbdDIl0APjj94zlxE6o1jM4an9gMSf6ruQLg0Vec4FuQUrQGFvGfSuGVUcBaJVUjFHUkYbhnexWqel3hzMcnIDZgKqXuwmVsPP0ImDigtASCa+wC6kU="
    on_success: always # default: change
    on_failure: always # default: always
    template:
      - "*%{repository_slug}* | *<%{build_url}|#%{build_number}>* | *%{branch}* | *<%{compare_url}|%{commit}>*"
      - "_%{commit_message}_"
      - "*%{result}* | *%{duration}* | %{message}"

script:
  - npm install codecov -g
  - npm run lint
  - npm run build
  - npm run build:dev
  - npm run build:prod
  - npm test

after_success:
  - codecov
