language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

notifications:
  email: false
  slack:
    rooms:
      - secure: "lOXYKEKV1UA1n7Z1o1HXEFfJurfJ5HD+hWA1EFERIzOjgZikrVRRZmzjUb0hNwOFIzTUkkRGSdExh5vNuZakQ0baz+P4yQ9ZQ5rCMaI4gdhXSdy0rLYUdmbazRpouRJf3/KFwxErnabEfpj+s/vRbEbSGuFTuARjRotRNPWz9I7GV7ZeheGBeOk3nvSA62oYrghTauK5bAaAd/0ILYCvKlsdO1t2MrlFhQK2q886P8YBTtbCMbInDCBwMrqNkmO6O29ZLL6kQ/JJoS+VCZAJ3tP1IEfqf+N/bB/UY5eYSPlfUYR/iLqngUGljONb4FoxZ0bQPL9fKdMkJlYInwPsD+JsdKA4ehs5AEgvzn7fs3o1FylPsc6ZMq+gyJawB1dJuOKbnJZWFZLxKVyl73Z/drhs2RIXitdDGrXoxr5nFgzR3Tf28U044DolrwTFNlxP+d39zYEk46n2v6vcm8fJ5Xkbkbwh/1R1vZFG9uxSquNB+8qqnTnXfNRF7viQbHruv4wvaL8sk+4dN6AicgAu58I5tvHWdjDDtaFzePYiqjoMzI567KYqIZT8+zK2udfgEHExCcnV2IZrkgyChAmPFmkfDtqrh4XwUO+mbBEW9OfaN19G2+TrcKFOB7KNYVyki55Kr8QB6M0t3zXU++UMWkVNjFwFBuit9whmMpNs6KI="
    on_success: always # default: change
    on_failure: always # default: always

script:
  - npm install codecov -g
  - npm run lint
  - npm run build
  - npm run build:dev
  - npm run build:prod
  - npm test

after_success:
  - codecov
