version: "{build}"

image: ubuntu

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

branches:
  only:
    - master
    - develop

stack: node $env:nodejs_version

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run build:dev
  - npm run build:prod
  - npm start

build: off
