name: build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [6, 8, 10]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn global add codecov
      - run: yarn install
      - run: yarn run lint
      - run: yarn run build
      - run: yarn run build:dev
      - run: yarn run build:prod
      - run: yarn test
      - name: Codecov
        uses: codecov/codecov-action@v1.0.12
